/**
 * Hard-reserved subdomains. Do not remove anything here without confirming
 * operationally — each entry is either a DNS-level collision (e.g. `www`,
 * `mail`, `cdn`), a product surface (e.g. `app`, `admin`, `docs`), or a
 * footgun shape that mirrors standard infra endpoints (e.g. `api`, `static`).
 */
export const RESERVED_SUBDOMAINS: ReadonlySet<string> = new Set([
  'www',
  'api',
  'app',
  'admin',
  'docs',
  'blog',
  'status',
  'help',
  'mail',
  'static',
  'cdn',
  'public',
  'assets',
  'auth',
  'login',
  'logout',
  'register',
  'signup',
  'signin',
  'billing',
  'support',
  'contact',
  'about',
  'terms',
  'privacy',
  'security',
  'abuse',
  'dashboard',
  'settings',
  'account',
  'accounts',
  'portal',
  'my',
  'dev',
  'staging',
  'preview',
  'render',
  'storybook',
  'internal',
  'private',
  'localhost',
  'test',
  'demo',
  'example',
  'null',
  'undefined',
  'root',
]);
